development:
  adapter: postgresql
  database: demo_app_development
  min_messages: warning
  host: localhost

test:
  adapter: postgresql
  min_messages: warning
  database: <%= ENV['DATABASE_NAME'] || 'demo_app_test' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USER'] || nil %>
  password: <%= ENV['DATABASE_PASSWORD'] || nil %>
